=== WearableAnalytics/wplug/test-resources/app-message.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "deviceInfo": {
      "type": "object",
      "properties": {
        "platform": { "type": "string" },
        "deviceId": { "type": "string" },
        "authorizationToken": { "type": "string" }
      },
      "required": ["platform", "deviceId", "authorizationToken"]
    },
    "batchInfo": {
      "type": "object",
      "properties": {
        "collectionStart": { "type": "string", "format": "date-time" },
        "collectionEnd": { "type": "string", "format": "date-time" }
      },
      "required": ["collectionStart", "collectionEnd"]
    },
    "measurements": {
      "type": "object",
      "properties": {
        "instantaneous": {
          "type": "array",
          "items": {}
        },
        "cumulative": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": { "type": "string" },
              "value": { "type": "number" },
              "unit": { "type": "string" },
              "periodStart": { "type": "string", "format": "date-time" },
              "periodEnd": { "type": "string", "format": "date-time" },
              "duration": { "type": "number" }
            },
            "required": ["type", "value", "unit", "periodStart", "periodEnd", "duration"]
          }
        },
        "duration": {
          "type": "array",
          "items": {}
        }
      },
      "required": ["instantaneous", "cumulative", "duration"]
    },
    "sourceName": { "type": "string" },
    "totalStepsToday": { "type": ["number", "null"] },
    "timestamp": { "type": "string", "format": "date-time" }
  },
  "required": ["deviceInfo", "batchInfo", "measurements", "sourceName", "totalStepsToday", "timestamp"]
}

=== WearableAnalytics/wplug/test-resources/example-message.json
{
  "deviceInfo": {
    "platform": "iOS",
    "deviceId": "unknown_device",
    "authorizationToken": "your_auth_token_here"
  },
  "batchInfo": {
    "collectionStart": "2025-11-17T18:53:55.034548",
    "collectionEnd": "2025-11-18T00:53:55.034548"
  },
  "measurements": {
    "instantaneous": [],
    "cumulative": [
      {
        "type": "STEPS",
        "value": 34,
        "unit": "COUNT",
        "periodStart": "2025-11-17T22:11:26.462",
        "periodEnd": "2025-11-17T22:12:15.033",
        "duration": 48
      },
      {
        "type": "STEPS",
        "value": 66,
        "unit": "COUNT",
        "periodStart": "2025-11-17T20:55:49.629",
        "periodEnd": "2025-11-17T21:03:57.823",
        "duration": 488
      },
      {
        "type": "STEPS",
        "value": 274,
        "unit": "COUNT",
        "periodStart": "2025-11-17T20:39:05.163",
        "periodEnd": "2025-11-17T20:43:56.521",
        "duration": 291
      },
      {
        "type": "STEPS",
        "value": 568,
        "unit": "COUNT",
        "periodStart": "2025-11-17T20:28:54.240",
        "periodEnd": "2025-11-17T20:38:26.831",
        "duration": 572
      },
      {
        "type": "STEPS",
        "value": 181,
        "unit": "COUNT",
        "periodStart": "2025-11-17T19:20:29.712",
        "periodEnd": "2025-11-17T19:23:18.410",
        "duration": 168
      },
      {
        "type": "ACTIVE_ENERGY_BURNED",
        "value": 0.6739999999999999,
        "unit": "KILOCALORIE",
        "periodStart": "2025-11-17T22:11:23.906",
        "periodEnd": "2025-11-17T22:12:15.029",
        "duration": 51
      },
      {
        "type": "ACTIVE_ENERGY_BURNED",
        "value": 0.766,
        "unit": "KILOCALORIE",
        "periodStart": "2025-11-17T20:55:41.961",
        "periodEnd": "2025-11-17T21:04:02.931",
        "duration": 500
      },
      {
        "type": "ACTIVE_ENERGY_BURNED",
        "value": 15.416,
        "unit": "KILOCALORIE",
        "periodStart": "2025-11-17T20:39:05.163",
        "periodEnd": "2025-11-17T20:44:01.629",
        "duration": 296
      },
      {
        "type": "ACTIVE_ENERGY_BURNED",
        "value": 13.518,
        "unit": "KILOCALORIE",
        "periodStart": "2025-11-17T20:28:51.684",
        "periodEnd": "2025-11-17T20:38:34.494",
        "duration": 582
      },
      {
        "type": "ACTIVE_ENERGY_BURNED",
        "value": 4.366,
        "unit": "KILOCALORIE",
        "periodStart": "2025-11-17T19:20:22.045",
        "periodEnd": "2025-11-17T19:23:26.074",
        "duration": 184
      }
    ],
    "duration": []
  },
  "sourceName": "Jakobs iPhone",
  "totalStepsToday": null,
  "timestamp": "2025-11-18T00:53:55.861405"
}
